### PR TITLE
8 fix/query visible users

### LINKED ISSUE #8: Query: Get all visibile users
### Description
- Return all users visible to the current authenticated user
- do not return users with visibility hidden
- do not return users with friend visibility that are not friends
- do not return users that have blocked you
- do not return users that have restricted you

This should be in backend/convex/users.ts as a query.

### PR DESCRIPTION
**Pull request by alexhtruong**
## Developer: Alex Truong

Closes #8 (fix)

### Pull Request Summary

Fixed `listVisibleUsers` query to filter out blocked and restricted users. Previously only filtered out people who had (our)self blocked/restricted.

### Screenshots/Screencast

N/A

### CODE REVIEW

File: apps/backend/convex/users.ts [hunk 1]
```diff
@@ -117,17 +117,31 @@ export const listVisibleUsers = query({
...
+        .map((b) => b.bannedUserId),
+    );
+
     const restrictedByOtherUserIds = new Set(
       restrictions
         .filter((r) => r.restrictedUserId === currentUser._id)
         .map((r) => r.fromUserId),
     );
 
+    const restrictedByCurrentUserIds = new Set(
```
Comment (wtheathOTG) [inline apps/backend/convex/users.ts]: The blockedByCurrentUserIds is a great catch! Im pretty sure restricting users should only hide our visibility from them, so the restrictedByCurrentUserIds is not neccessary here. Delete this then push the code and I'll merge. Great work!

**Review by wtheathOTG — APPROVED** [review]
